services:
  postgres:
    image: postgres:15
    container_name: chess_api_db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
